<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ParadoxTranslationHelper</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
	<AssemblyVersion>1.0.1.203</AssemblyVersion>
	<FileVersion>1.0.1.203</FileVersion>
</PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ParadoxTranslationHelper_Test" />
  </ItemGroup>
  <ItemGroup>
      <None Remove="ParadoxTranslationHelper.xml" />
    </ItemGroup>
    <ItemGroup>
      <Content Include="ParadoxTranslationHelper.xml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="coverlet.collector">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Serilog" />
      <PackageReference Include="Serilog.Sinks.Console" />
      <PackageReference Include="Serilog.Sinks.File" />
      <PackageReference Include="Serilog.Sinks.Map" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Repositories\" />
    </ItemGroup>
</Project>